apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: afm-ingress
  namespace: africa-frontier-markets
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - api.africafrontiermarkets.com
      secretName: afm-tls
  rules:
    - host: api.africafrontiermarkets.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8000
