apiVersion: v1
kind: Secret
metadata:
  name: afm-secrets
  namespace: africa-frontier-markets
type: Opaque
stringData:
  SECRET_KEY: REPLACE_WITH_48_PLUS_CHAR_SECRET
  DATABASE_URL: REPLACE_WITH_DB_URL
  REDIS_URL: REPLACE_WITH_REDIS_URL
  KORA_API_KEY: REPLACE
  KORA_SECRET_KEY: REPLACE
  FINCRA_API_KEY: REPLACE
  FINCRA_SECRET_KEY: REPLACE
